######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 14 03:15:44 2014
######################################################################

TEMPLATE = app
TARGET = Q-Game
DEPENDPATH += .
INCLUDEPATH += .

# Output
DESTDIR = build

# Input
QT += opengl
HEADERS += CrmGlWindow.h
SOURCES += CrmGlWindow.cpp main.cpp
